## TAG ##
# Browser
windowrule = tag +browser, match:class ^(zen-browser|chromium|qutebrowser)$
# Game
windowrule = tag +game, match:class ^(steam|hydralauncher|net.lutris.Lutris|com.usebottles.bottles)$
# Code Editor
windowrule = tag +code_editor, match:class ^(code|antigravity|obsidian)$
# Dev Tools
windowrule = tag +tools, match:class ^(MongoDB Compass|com.obsproject.Studio|Altair GraphQL Client|bruno)$ 
# Communication
windowrule = tag +communication, match:class ^(discord)$
# Audio
  windowrule = tag +audio, match:class ^(spotify|YouTube Music Desktop App|org.pulseaudio.pavucontrol|GalaxyBudsClient)$

## OPACITY ##
windowrule = opacity 0.95 0.95, match:tag browser 
windowrule = opacity 0.9 0.9, match:tag game_launcher
windowrule = opacity 0.9 0.9, match:tag code_editor
windowrule = opacity 0.9 0.9, match:tag tools 
windowrule = opacity 0.9 0.9, match:tag communication
windowrule = opacity 0.9 0.9, match:tag audio
windowrule = opacity 0.9 0.9, match:class rog-control-center
windowrule = opacity 0.9 0.9, match:class nvidia-settings
windowrule = opacity 0.9 0.9, match:class thunar
windowrule = opacity 0.9 0.9, match:class blueman-manager

## Custom Startup ##
# Yazi
windowrule = float on, match:title ^(yazi)$
windowrule = center on, match:title ^(yazi)$
windowrule = size 800 500, match:title ^(yazi)$
# Blueman
windowrule = float on, match:class blueman-manager
windowrule = size 400 400, match:class blueman-manager
# Pavucontrol
windowrule = float on, match:class pavucontrol
windowrule = size 400 400, match:class pavucontrol
