## TAG ##
# Browser
windowrule = tag +browser, match:class zen-browser
windowrule = tag +browser, match:class chromium
windowrule = tag +browser, match:class qutebrowser
# Music
windowrule = tag +music_player, match:class spotify
windowrule = tag +music_player, match:class ^(YouTube Music Desktop App)$
# Game
windowrule = tag +game_launcher, match:class steam
windowrule = tag +game_launcher, match:class hydralauncher 
windowrule = tag +game_launcher, match:class net.lutris.Lutris
windowrule = tag +game_launcher, match:class com.usebottles.bottles)


## OPACITY ##
windowrule = opacity 0.95 0.95, match:tag browser 
windowrule = opacity 0.9 0.9, match:tag game_launcher
windowrule = opacity 0.9 0.9, match:tag music_player
windowrule = opacity 0.9 0.9, match:class discord
windowrule = opacity 0.9 0.9, match:class com.obsproject.Studio
windowrule = opacity 0.9 0.9, match:class rog-control-center
windowrule = opacity 0.9 0.9, match:class nvidia-settings
windowrule = opacity 0.9 0.9, match:class thunar
windowrule = opacity 0.9 0.9, match:class blueman-manager
windowrule = opacity 0.9 0.9, match:class org.pulseaudio.pavucontrol

## Custom Startup ##
# Yazi
windowrule = float on, match:title ^(yazi)$
windowrule = center on, match:title ^(yazi)$
windowrule = size 800 500, match:title ^(yazi)$
# Blueman
windowrule = float on, match:class blueman-manager
windowrule = size 400 400, match:class blueman-manager
# Pavucontrol
windowrule = float on, match:class pavucontrol
windowrule = size 400 400, match:class pavucontrol

# windowrule = size 1280 800, match:class hydralauncher
# windowrule = center on, match:class hydralauncher
