## TAG ##
windowrulev2 = tag +term, class:(kitty)
windowrulev2 = tag +term, class:(st)
windowrulev2 = tag +browser, class:(firefox)
windowrulev2 = tag +browser, class:(chromium)
windowrulev2 = tag +browser, class:(Google-chrome)
windowrulev2 = tag +browser, class:(zen-alpha)
windowrulev2 = tag +browser, class:(qutebrowser)

## OPACITY ##
windowrulev2 = opacity 0.9, tag:term 
windowrulev2 = opacity 0.9 0.9, tag:browser 
windowrulev2 = opacity 0.9 0.9, class:^(dolphin)
# windowrulev2 = opacity, 0.80 0.80, class:^(intellij)
windowrulev2 = opacity 0.9 0.9, class:^(blueman-manager)
windowrulev2 = opacity 0.9 0.9, class:^(pavucontrol)

## Custom Startup ##
windowrule = float, kitty
windowrule = float, blueman-manager
windowrule = float, pavucontrol 
windowrule = size 400 400, blueman-manager
windowrule = size 800 500, kitty
windowrule = size 400 400, pavucontrol 
